---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-svcs-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: "istio-svcs-cert"
    hosts:
    {{- toYaml .Values.dnsNames | nindent 4 }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali-virtualservice
  namespace: istio-system
spec:
  hosts:
  {{- toYaml .Values.kiali.dnsName | nindent 2 }}
  gateways:
  - istio-svcs-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 20001
        host: kiali
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tracing-virtualservice
  namespace: istio-system
spec:
  hosts:
  {{- toYaml .Values.tracing.dnsName | nindent 2}}
  gateways:
  - istio-svcs-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: tracing
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-grafana-virtualservice
  namespace: istio-system
spec:
  hosts:
  {{- toYaml .Values.istioGrafana.dnsName | nindent 2}}
  gateways:
  - istio-svcs-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 3000
        host: grafana
---
